### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException on MovieCreator.build()

### ISSUE THREAD

**Issue by 73k05** [deepandroid/video-trimmer#8]
Hi,

thank you for this cool lib. I've noticed a crash from my community, would you like to have a look at it?

```
Fatal Exception: java.lang.RuntimeException: A cast to int has gone wrong. Please contact the mp4parser discussion group (3673738558)
       at com.googlecode.mp4parser.util.CastUtils.l2i(CastUtils.java:30)
       at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
       at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
       at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
       at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
       at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
       at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
       at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
       at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
       at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
       at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
       at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
       at life.knowledge4.videotrimmer.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.java:72)
       at life.knowledge4.videotrimmer.utils.TrimVideoUtils.startTrim(TrimVideoUtils.java:65)
       at life.knowledge4.videotrimmer.K4LVideoTrimmer$5.execute(K4LVideoTrimmer.java:354)
       at life.knowledge4.videotrimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
This thread might help https://github.com/sannies/mp4parser/issues/126

**Comment by 73k05** [comment]
I mixed up with this lib: https://github.com/titansgroup/k4l-video-trimmer -_-

**Comment by 73k05** [comment]
Maybe we should update the m4parser lib in the build.gradle:
https://github.com/deepandroid/video-trimmer/blob/8dbbd6d45e9c7a5825371dc005727b8e7de72d12/videotrimmer/build.gradle#L44

```
implementation 'org.mp4parser:isoparser:1.9.27'
```
